micronaut:
    application:
        name: demo
    server:
        port: 9001

datasources:
    default:
        url: jdbc:postgresql://localhost:5432/postgres
        driverClassName: org.postgresql.Driver
        username: postgres
        password: postgres
        dialect: POSTGRES

liquibase:
    datasources:
        default:
            change-log: classpath:db/changelog.yml
