micronaut:
    application:
        name: demo
    server:
        port: 9001

datasources:
    default:
        url: jdbc:postgresql://localhost:5432/postgres?currentSchema=demo
        driverClassName: org.postgresql.Driver
        username: postgres
        password: postgres
        dialect: POSTGRES

flyway:
    datasources:
        default:
            url: jdbc:postgresql://localhost:5432/postgres?currentSchema=demo
            username: postgres
            password: postgres
    locations: classpath:db/migration
